### ISSUE TITLE
Replace unstated for regular context in locales

### ISSUE THREAD

**Issue by dariocravero** [viewstools/morph#113]
When we introduced locales in Views, there was confusion around the React community on how to use the new context API. Particularly around passing functions down to a consumer so it can change the value of the provider. This seems to have settled now and people are happy to include the functions in the provider's state. That's why we were using `unstated` in the first place. I suggest we swap that and use context directly. It may also impact how we get the initial locale, as we may be able to provide a default function to locate it that gets overwritten through props in this new provider.

**Comment by amymc** [comment]
Just putting this on the issue for later, otherwise I’ll forget. 

I’ve replaced unstated with regular context on [this branch](https://github.com/viewstools/morph/compare/context-locales)

There’s some weird shit going on with imports when I run the tests that’s confusing me.

For `react-dom Locals` it’s trying to import the consumer like this:
`import LocalConsumer from './LocalConsumer.view.js`
It should be this: `import { LocalConsumer } from '../LocalContext.js’;`

The weird thing is if I run the same view in a sample project the compiled output has the correct import. 

And I see that previously the test was importing the container like this:
`import LocalContainer from './LocalContainer.view.js`
Which was also wrong, but again that was not it was actually being imported in an actual project.

On the `LocalsFormat` test there’s no imports at all for the consumer (or for the container on the previous version)

So I'm not sure if the tests were already banjaxed, or if there’s some reason they’re not supposed to match the real world compiled output.
