### ISSUE TITLE
Certain properties should only be applicable to specific blocks

### ISSUE THREAD

**Issue by amymc** [viewstools/morph#30]
Certain properties should not be applied to all block types as they will have no effect when applied.
Examples:
- Font related properties such as `font-family` and `font-weight`, should only be applicable to `text` blocks.
- `OnClick` event handlers should not be applicable to `text` blocks.

**Comment by jgtoriginal** [comment]
@amymc @dariocravero do we have a full list of properties ordered by block types to which they should affect? or shall we narrow down the scope to the 2 examples given?

**Comment by jgtoriginal** [comment]
@amymc @dariocravero what do you guys think about this approach??
we tell devs when a font related prop doesn't apply to non fontable blocks.
I personally don't think is good not to parse it, since if not applicable it will render no effect to the block and will hassle devs. what you guys reckon?
For the onClick event, that's broader, I don't know whats the logic behind that implementation @dariocravero cause I think that's not really native, is it?

**Comment by jgtoriginal** [comment]
Also, just checking we there is also this function `isValidPropertyForBlock` on both `react-dom` and `react-native`. Thing this that it happens after the `parse`. any thoughts @dariocravero
