### ISSUE TITLE
Performant tables in Views syntax

### ISSUE THREAD

**Issue by tombrewsviews** [viewstools/morph#59]
Here's the Views syntax that we would see work with the ReactVirtualized and FlatList components to enable full control of the styling in blocks format.

```
Table List
the data would look like [{id: 1, name: 'tom'}, {id: 2, name: 'dario'}]
from <
Name Column
key name
Text
isHeader true
text Name

TableCell
isCell true


Surname Column
key surname
Text
isHeader true
text Surname

TableCell
isCell true


Phone Column
key phone
Text
isHeader true
text phone

TableCell
isCell true
```

Links to components that we would see as good candidates for the table solutions for web and for native
https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md (edited)
https://facebook.github.io/react-native/docs/flatlist.html

**Comment by amymc** [comment]
Some questions for discussion:

1. Do want to have the table as a variation of `List` as per the example above, or do we want to have a new component type of `Table`?

2. So if we are keeping it as a variant of `List`, then I guess the user would signal that it's a table by including `cell`s. Then, that could look something like this...
```
Cell Text
isCell true
margin 0
padding 0
borderBottomStyle solid
borderBottomColor black
borderBottomWidth 1
```
But if we're making a new `Table` component, then I think `cell` becomes redundant because cells will be created depending on how much data is in the `from` slot, even if you don't declare a `cell` the cells would be created. The cell styles could be declared on the `column` itself like this...
```
Name Column
key name
margin 0
padding 0
borderBottomStyle solid
borderBottomColor black
borderBottomWidth 1
```
In the compiled output, this is actually how we would be doing it, we would pass the cell styles to the column. But conceptually I think this is kind of confusing 😬

3. We don't have a row element so how would we handle row styles? React virtualized requires `rowHeight`,  we could just put it directly on the `Table`/`List` element like this...
```
Results Table
from <
rowHeight 20
```
But how would we handle row styles like this? ...
```
"&:hover": {
  backgroundColor: "grey",
  color: "white"
}
```
4. React virtualized also expects `headerHeight`. Do we want to make that optional and if the user doesn't supply it just assume it's the same as `rowHeight`?

Sandbox for reference: https://codesandbox.io/s/z2n53v80rl
Possible `view` that could generate that sandbox (except for the hover state):

```
Results List
from <
headerHeight 40
rowHeight 20
Name Column
key name
Text
isHeader true
text Name

Cell


Location Column
key location
Text
isHeader true
text location

Cell


Description Column
key description
Cell


// in Cell.view
Cell Text
isCell true
margin 0
padding 0
borderBottomStyle solid
borderBottomColor black
borderBottomWidth 1
```

**Comment by amymc** [comment]
Just putting this here after our call so I don't forget it

```
Table
from <
rowBackgroundColor white
rowBackgroundColorAlternate black
when <hover
rowBackgroundColor black
rowBackgroundColorAlternate white
```

**Comment by amymc** [comment]
For now, when it comes to styling rows, are we only allowing for`rowBackgroundColor` and `rowBackgroundColorAlternate`? In the sandbox, I had originally put a bottom border on individual cells but we can achieve the same effect by applying that border to the row instead and I think it makes more sense (updated sandbox - https://codesandbox.io/s/z2n53v80rl). So maybe we should allow for `rowBorderBottom` etc, as well? 

In which case, it would be less likely that a user would want to apply styles to individual cells, then the cell would just look something like this...
```
Cell Horizontal
isCell true
```
But, without styles, isn't that kind of meaningless? The cell would render anyway because they’re created based on the data in the `from`.

**Comment by dariocravero** [comment]
I guess that would make sense, however what if someone wants to do `rowBorderTop` instead? Should we add that too? Also, if we add this we'd need to add the expanded versions `rowBorderBottomStyle`, `rowBorderBottomColor`, and `rowBorderBottomWidth` to be consistent with the rest of Views. I don't know what does @tombrewsviews thinks about this?

Also, what do you mean by this?
> But, without styles, isn't that kind of meaningless? The cell would render anyway because they’re created based on the data in the from.

**Comment by amymc** [comment]
I mean,  this snippet below doesn't actually do anything.
```
Cell Horizontal
isCell true
```

The cells will be rendered based on the `key` of the column.
The only point of declaring the cell in the `view` is to give it styles, but if we're not applying any styles to the cell then that snippet has no function.

Does that make sense, or have it got I wrong?

**Comment by dariocravero** [comment]
Well, for consistency with the List, the cell will be a view itself, so the way I see it, it wouldn't really matter all that much, eg:

```
Table
Column
key name
MyHeader
isHeader true
text Name

NameCell
isCell true
```

Then `NameCell.view` can be anything but it wouldn't have the `isCell` prop on it because it's outside of its scope to know it's a cell.

Did I miss something?

**Comment by amymc** [comment]
Ok, that's grand. But if we're just applying styles to the row and we're not applying any styles to the cell,  what do you see being in the file `NameCell.view`?

**Comment by dariocravero** [comment]
Anything from text to a capture or a more complex widget, at least that's what I understood @tombrewsviews was after

**Comment by tombrewsviews** [comment]
Correct. Ideally a cell would be anything, input, read only text, dropdown.

**Comment by dariocravero** [comment]
something to consider for lists in web https://github.com/bvaughn/react-window perhaps?

**Comment by amymc** [comment]
Cool. The advantage over 'react-virtualized' being that it'll be easier to do dynamic sizing and it's a smaller package?

**Comment by dariocravero** [comment]
Yeah it looks like it. It doesn’t seem to do tables though. Worth exploring
it anyway I think.
